services:

  api:
    build: ./apps/api
    ports:
      - "8000:8000"

  bot:
    build: ./apps/github-app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16

  redis:
    image: redis:7
